SELECT ID,
       ((EXTRACT(YEAR FROM FINISH_DATE) - EXTRACT(YEAR FROM START_DATE)) * 12) +
       (EXTRACT(MONTH FROM FINISH_DATE) - EXTRACT(MONTH FROM START_DATE)) AS MONTH_COUNT
FROM project
GROUP BY ID
ORDER BY MONTH_COUNT DESC
LIMIT 1;